#!/usr/local/bin/perl
# script to run RPC tests one at a time and record the proceedings

use strict;
use warnings;

# some parameters to be specified
my $doamin    = "admig";
my $logfile   = "./smbtorture-run" . scalar(localtime) . ".log";
my $username  = "administrator";
my $password  = "migs*21";
my $filerip   = "10.72.205.213";
my $filer_dir = "home";

my @local =
  qw/LOCAL-BINDING LOCAL-NTLMSSP LOCAL-MESSAGING LOCAL-IRPC LOCAL-STRLIST LOCAL-FILE LOCAL-IDTREE LOCAL-ICONV LOCAL-SOCKET LOCAL-PAC LOCAL-REGISTRY LOCAL-RESOLVE LOCAL-SDDL LOCAL-NDR LOCAL-TDR LOCAL-EVENT LOCAL-TORTURE LOCAL-DBSPEED LOCAL-TALLOC LOCAL-REPLACE LOCAL-CRYPTO-SHA1 LOCAL-CRYPTO-MD4 LOCAL-CRYPTO-MD5 LOCAL-CRYPTO-HMACMD5 LOCAL-CRYPTO-HMACSHA1/;
my @net =
  qw/NET-USERINFO NET-USERADD NET-USERDEL NET-USERMOD NET-DOMOPEN NET-API-LOOKUP NET-API-LOOKUPHOST NET-API-LOOKUPPDC NET-API-LOOKUPNAME NET-API-CREATEUSER NET-API-DELETEUSER NET-API-MODIFYUSER NET-API-USERINFO NET-API-USERLIST NET-API-RPCCONN-BIND NET-API-RPCCONN-SRV NET-API-RPCCONN-PDC NET-API-RPCCONN-DC NET-API-RPCCONN-DCINFO NET-API-LISTSHARES NET-API-DELSHARE NET-API-DOMOPENLSA NET-API-DOMCLOSELSA NET-API-DOMOPENSAMR NET-API-DOMCLOSESAMR NET-API-BECOME-DC/;
my @smb2 =
  qw/SMB2-CONNECT SMB2-SCAN SMB2-SCANGETINFO SMB2-SCANSETINFO SMB2-SCANFIND SMB2-GETINFO SMB2-SETINFO SMB2-FIND SMB2-LOCK SMB2-NOTIFY/;
my @rpc =
  qw/RPC-ECHO RPC-RPC-DFS RPC-UNIXINFO RPC-EVENTLOG RPC-ATSVC RPC-WKSSVC RPC-LSA RPC-LSALOOKUP RPC-LSA-GETUSER RPC-SECRETS RPC-SPOOLSS RPC-SAMR RPC-SAMR-USERS   RPC-SAMR-PASSWORDS RPC-NETLOGON RPC-SAMLOGON RPC-SAMSYNC RPC-SCHANNEL RPC-SRVSVC RPC-SVCCTL RPC-EPMAPPER RPC-WINREG RPC-INITSHUTDOWN RPC-OXIDRESOLVE RPC-REMACT RPC-MGMT RPC-SCANNER RPC-AUTOIDL RPC-COUNTCALLS RPC-MULTIBIND RPC-AUTHCONTEXT RPC-BINDSAMBA3 RPC-NETLOGSAMBA3 RPC-SAMBA3SESSIONKEY RPC-SAMBA3-SRVSVC RPC-SAMBA3-SHARESEC RPC-SAMBA3-GETUSERNAME RPC-SAMBA3-LSA RPC-SAMBA3-SPOOLSS RPC-SAMBA3-WKSSVC RPC-RPC-SAMBA3-WINREG RPC-DRSUAPI RPC-CRACKNAMES RPC-ROT RPC-DSSETUP RPC-ALTERCONTEXT RPC-JOIN RPC-DSSYNC RPC-BENCH-RPC RPC-ASYNCBIND/;
my @raw =
  qw/RAW-BENCH-OPLOCK RAW-BENCH-LOCK RAW-QFSINFO RAW-QFILEINFO RAW-SFILEINFO RAW-SFILEINFO-BUG RAW-SEARCH RAW-CLOSE RAW-OPEN RAW-MKDIR RAW-OPLOCK RAW-NOTIFY RAW-MUX RAW-IOCTL RAW-CHKPATH RAW-UNLINK RAW-READ RAW-WRITE RAW-LOCK RAW-CONTEXT RAW-RENAME RAW-SEEK RAW-EAS RAW-STREAMS RAW-ACLS RAW-COMPOSITE RAW-SAMBA3HIDE RAW-SAMBA3CLOSEERR RAW-SAMBA3CHECKFSP RAW-SAMBA3BADPATH RAW-SCAN-EAMAX/;
my @nbt =
  qw/NBT-REGISTER NBT-WINS NBT-DGRAM NBT-WINSREPLICATION NBT-BENCH NBT-BENCH-WINS/;
my @base =
  qw/BASE-LOCK BASE-DELETE BASE-DELAYWRITE BASE-ALIASES BASE-FDPASS BASE-UNLINK BASE-ATTR BASE-TRANS2 BASE-NEGNOWAIT BASE-DIR1 BASE-DIR2 BASE-DENY1 BASE-DENY2 BASE-DENY3 BASE-DENYDOS BASE-NTDENY1 BASE-NTDENY2 BASE-TCON BASE-TCONDEV BASE-VUID BASE-RW1 BASE-OPEN BASE-DEFER_OPEN BASE-XCOPY BASE-IOMETER BASE-RENAME BASE-PROPERTIES BASE-MANGLE BASE-OPENATTR BASE-CHARSET BASE-CHKPATH BASE-SECLEAK BASE-DISCONNECT BASE-SAMBA3ERROR BASE-CASETABLE BASE-UTABLE BASE-SMB BASE-TRANS2-SCAN BASE-NTTRANS BASE-BENCH-HOLDCON BASE-BENCH-READWRITE BASE-BENCH-TORTURE BASE-SCAN-PIPE_NUMBER BASE-SCAN-IOCTL BASE-SCAN-MAXFID/;
my @others =
  qw/ BENCH-NBENCH RAP-BASIC RAP-SCAN LDAP-BENCH-CLDAP LDAP-BASIC LDAP-CLDAP LDAP-SCHEMA/;

my @rpctests = ( @local, @net, @smb2, @rpc, @raw, @nbt, @base, @others );

open( LOGHANDLE, ">", $logfile )
  || die "Not able to create the log File \n " . $@;

foreach my $rpc (@rpctests) {
    print "\n Running test $rpc";
    print LOGHANDLE "\n Running test $rpc";

#	my $output = qx{./smbtorture.old //$filerip/$filer_dir -W $doamin -U $username%$password -L $rpc} ;
    my $output =
qx{/u/saurabhg/tools/samba-4-old/source/bin/smbtorture //10.72.205.31/home -W admig -U administrator%migs*21 $rpc};
    print LOGHANDLE $output;
    print $output;
}
close LOGHANDLE;

